// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-learning-paths.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_learning_paths_default = defineTool({
  name: "list_learning_paths",
  title: "Listar trilhas de aprendizagem",
  description: "Lista as trilhas de aprendizagem (learning paths) do app, opcionalmente filtradas por \xE1rea STEM (science, technology, engineering, math).",
  inputSchema: {
    stem_area: z.enum(["science", "technology", "engineering", "math"]).optional().describe("Filtra por \xE1rea STEM."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de itens (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stem_area, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db(ctx).from("learning_path_content").select("*").order("sort_order", { ascending: true });
    if (stem_area) q = q.eq("stem_area", stem_area);
    q = q.limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-modules.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_modules_default = defineTool2({
  name: "list_modules",
  title: "Listar m\xF3dulos",
  description: "Lista os m\xF3dulos de estudo do app, opcionalmente filtrados por \xE1rea STEM.",
  inputSchema: {
    stem_area: z2.enum(["science", "technology", "engineering", "math"]).optional(),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stem_area, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db2(ctx).from("modules_content").select("*").order("sort_order", { ascending: true });
    if (stem_area) q = q.eq("stem_area", stem_area);
    q = q.limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-experiments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_experiments_default = defineTool3({
  name: "list_experiments",
  title: "Listar experimentos do laborat\xF3rio",
  description: "Lista os experimentos do laborat\xF3rio virtual, opcionalmente filtrados por \xE1rea STEM.",
  inputSchema: {
    stem_area: z3.enum(["science", "technology", "engineering", "math"]).optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stem_area, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db3(ctx).from("experiments_content").select("*").order("sort_order", { ascending: true });
    if (stem_area) q = q.eq("stem_area", stem_area);
    q = q.limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-career-areas.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_career_areas_default = defineTool4({
  name: "list_career_areas",
  title: "Listar \xE1reas de atua\xE7\xE3o",
  description: "Lista as \xE1reas de atua\xE7\xE3o (carreiras STEM) e as mulheres inspiradoras associadas.",
  inputSchema: {
    stem_area: z4.enum(["science", "technology", "engineering", "math"]).optional(),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stem_area, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db4(ctx).from("career_areas_content").select("*").order("sort_order", { ascending: true });
    if (stem_area) q = q.eq("stem_area", stem_area);
    q = q.limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool5({
  name: "list_blog_posts",
  title: "Listar posts do blog",
  description: "Lista posts publicados do blog do app, do mais recente para o mais antigo.",
  inputSchema: {
    category: z5.string().optional().describe("Filtra por categoria."),
    limit: z5.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db5(ctx).from("blog_posts").select("id,title,excerpt,category,author_name,emoji,read_time,cover_image,published,created_at").eq("published", true).order("created_at", { ascending: false });
    if (category) q = q.eq("category", category);
    q = q.limit(limit ?? 20);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
function db6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_progress_default = defineTool6({
  name: "get_my_progress",
  title: "Ver meu progresso",
  description: "Retorna o progresso da usu\xE1ria autenticada: perfil, pontos/n\xEDvel por \xE1rea STEM, li\xE7\xF5es, m\xF3dulos e experimentos conclu\xEDdos.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = db6(ctx);
    const userId = ctx.getUserId();
    const [profile, progress, lessons, modules, experiments] = await Promise.all([
      client.from("profiles").select("id,name,email,age,interests").eq("id", userId).maybeSingle(),
      client.from("user_progress").select("*").eq("user_id", userId),
      client.from("completed_lessons").select("*").eq("user_id", userId),
      client.from("completed_modules").select("*").eq("user_id", userId),
      client.from("completed_experiments").select("*").eq("user_id", userId)
    ]);
    const payload = {
      profile: profile.data,
      progress_by_area: progress.data ?? [],
      completed_lessons: lessons.data ?? [],
      completed_modules: modules.data ?? [],
      completed_experiments: experiments.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pocdgiysxjipmlmyzfhd";
var mcp_default = defineMcp({
  name: "ciencia-magica-meninas-mcp",
  title: "Ci\xEAncia M\xE1gica Meninas MCP",
  version: "0.1.0",
  instructions: "Ferramentas do app Ci\xEAncia M\xE1gica Meninas: consulta a trilhas de aprendizagem, m\xF3dulos, experimentos do laborat\xF3rio, \xE1reas de atua\xE7\xE3o (carreiras STEM), posts do blog e o progresso da usu\xE1ria autenticada. Todas as ferramentas respeitam as permiss\xF5es da conta conectada.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_learning_paths_default,
    list_modules_default,
    list_experiments_default,
    list_career_areas_default,
    list_blog_posts_default,
    get_my_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
